Contient 221 mesures de vitesse du vent au Nebraska en 2001.

Source : https://github.com/plotly/datasets/blob/master/wind_speed_laurel_nebraska.csv

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("wind_speed_laurel_nebraska.csv")

In [3]:
df.columns.values

array(['Ten_Min_Std_Dev', 'Time', 'Ten_Min_Sampled_Avg'], dtype=object)

In [4]:
std10 = np.array(df.Ten_Min_Std_Dev)
std10[0:10]


array([2.73, 1.98, 1.87, 2.03, 3.1 , 2.3 , 2.46, 1.87, 1.71, 1.76])

In [5]:
dbn = len(std10)
dbn

221

In [6]:
mu10 = np.array(df.Ten_Min_Sampled_Avg)
mu10[0:10]

array([22.3, 23. , 23.3, 22. , 20.5, 25.2, 24.8, 24. , 22.9, 17.9])

In [7]:
datelist = list(df.Time)
datelist[0:10]

['2001-06-11 11:00',
 '2001-06-11 11:10',
 '2001-06-11 11:20',
 '2001-06-11 11:30',
 '2001-06-11 11:40',
 '2001-06-11 11:50',
 '2001-06-11 12:00',
 '2001-06-11 12:10',
 '2001-06-11 12:20',
 '2001-06-11 12:30']

Pour récupérer le jour, le mois et l'année, on extrait les caractères et on les convertit en entier.

In [8]:
datelist[0]

'2001-06-11 11:00'

In [9]:
year = int(datelist[0][0:4])
year

2001

In [10]:
month = int(datelist[0][5:7])
month

6

In [11]:
day = int(datelist[0][8:10])
day

11

On stocke ces données dans un array numpy.

In [12]:
data = np.zeros((dbn,5))
for i in range(dbn):
    year = int(datelist[0][0:4])
    month = int(datelist[0][5:7])
    day = int(datelist[0][8:10])
    data[i,0] = year
    data[i,1] = month
    data[i,2] = day
    data[i,3] = mu10[i]
    data[i,4] = std10[i]   

In [13]:
data[0:10,:]

array([[2.001e+03, 6.000e+00, 1.100e+01, 2.230e+01, 2.730e+00],
       [2.001e+03, 6.000e+00, 1.100e+01, 2.300e+01, 1.980e+00],
       [2.001e+03, 6.000e+00, 1.100e+01, 2.330e+01, 1.870e+00],
       [2.001e+03, 6.000e+00, 1.100e+01, 2.200e+01, 2.030e+00],
       [2.001e+03, 6.000e+00, 1.100e+01, 2.050e+01, 3.100e+00],
       [2.001e+03, 6.000e+00, 1.100e+01, 2.520e+01, 2.300e+00],
       [2.001e+03, 6.000e+00, 1.100e+01, 2.480e+01, 2.460e+00],
       [2.001e+03, 6.000e+00, 1.100e+01, 2.400e+01, 1.870e+00],
       [2.001e+03, 6.000e+00, 1.100e+01, 2.290e+01, 1.710e+00],
       [2.001e+03, 6.000e+00, 1.100e+01, 1.790e+01, 1.760e+00]])

In [14]:
np.savetxt("wind_speed_laurel_nebraska-clean.csv",data, fmt='%.1f', header="Year Month Day Ten_Min_Avg Ten_Min_StD", comments="")